### ISSUE TITLE
How to enable

### ISSUE THREAD

**Issue by apexred** [joomdev/JD-Profiler#2]
Hello Chetan,

I have installed the JD Profiler module and created a couple of profiles and teams.  But it's not obvious to me how I create a menu link. (Apologies, but I don't know Joomla very well.  We are currently using TLP Team and the TLP Team module appears in the "Menu Item Type" pop-up.  But there's no JD Profiler module to select.)

Thanks in advance for any help you can provide

**Comment by Sumesh577** [comment]
Hey,

Sorry to inform you but we currently do not have this feature in our JD Profiler-lite version, you need to link that via module as follows: 

Step 1:- Go the Extension->Modules-> JD Profiler
Step 2:- Choose JD Profiler Module
Step 3:- You have to select the desired position where you want to display (https://www.screencast.com/t/2ceN113q)
Step 4:- Select the desired page from the Menu Assignment tab (https://www.screencast.com/t/H7fSSqA40mq)


Thanks
Sumesh
