### ISSUE TITLE
Social media links disappear

### ISSUE THREAD

**Issue by apexred** [joomdev/JD-Profiler#4]
If I add one or two links, eveything is fine.

HHowever, add a third Social Media link, click save and all three links disappear.  Ouch.

(Nishtha, do the devs follow these open issues?)

**Comment by Nishtha003** [comment]
Yes they do.

**Comment by chetanmadaan** [comment]
@apexred please reinstall using the url here: https://github.com/joomdev/JD-Profiler/archive/master.zip

Thanks,
Chetan
